
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: kubeintel
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: kubeops-api
        static_configs:
          - targets:
              - kubeops-api-service:5000
        metrics_path: /metrics
