apiVersion: apps/v1
kind: Deployment

metadata:
  name: kubeops-ui
  namespace: kubeintel
  labels:
    app: kubeops-ui
    version: "2.0.0"

spec:
  replicas: 2

  selector:
    matchLabels:
      app: kubeops-ui

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

  template:
    metadata:
      labels:
        app: kubeops-ui
        version: "2.0.0"

      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8501"
        prometheus.io/path: "/metrics"

    spec:
      containers:

        - name: kubeops-ui

          image: 164092711400.dkr.ecr.us-east-1.amazonaws.com/kubeops-ui:v1.0

          imagePullPolicy: Always

          ports:
            - containerPort: 8501

          env:
            - name: API_BASE_URL
              value: "http://kubeops-api-service:5000"

          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"

            limits:
              memory: "512Mi"
              cpu: "500m"

          livenessProbe:
            httpGet:
              path: /
              port: 8501

            initialDelaySeconds: 20
            periodSeconds: 20
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /
              port: 8501

            initialDelaySeconds: 10
            periodSeconds: 10

          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false

      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100

              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - kubeops-ui

                topologyKey: kubernetes.io/hostname